name: MinecraftCommerce-MySQL
description: MySQL gateway type for MinecraftCommerce
author: Tim van Dijkhuizen
version: "1.2.1"
api-version: 1.13
main: nl.timvandijkhuizen.commerce.mysql.CommerceMySQL
depend: [SpigotUtils, MinecraftCommerce]